# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
locale                   : "fr-FR"
title                    : "Catherine Phan van"
seo_title                : "Catherine Phan van"
title_separator          : "-"
subtitle                 : "Autrice"
name                     : "Catherine Phan van"
description              : "Site officiel de l'autrice Catherine Phan van"
url                      : "https://catherinephanvan.fr"
logo                     : "/assets/images/logo_CPV_transparent.webp"
masthead_title           : "Accueil"
consents                 : "/consents.html"
mentions-legales         : "/mentions-legales"
date_format              : "%d/%m/%Y"
breadcrumbs              : true
search                   : true
search_provider          : "google"
future                   : false

author:
  name      : "Catherine Phan van"
  avatar    : "/assets/images/C_Phanvan.webp"
  bio       : |
    Catherine Phan van est originaire du Haut-Doubs, qu'elle a quitté pour s'installer près de Bordeaux, où elle vit depuis 2008.

    Ingénieure de formation mais autrice de cœur depuis sa plus tendre adolescence, elle a franchi le pas des soumissions en répondant à partir de 2021 à des appels à textes, ce qui lui vaut à ce jour une quinzaine de nouvelles publiées.

    Si elle ne s'est pas absentée quelques heures de ce monde pour se promener en compagnie de ses personnages, vous la trouverez peut-être occupée à déguster une tisane devant un bon roman, tirer des sons inharmonieux de sa clarinette, ou confectionner le pire gâteau jamais imaginé…
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/cathphanvan/"
    - label: "Threads"
      icon: "fas fa-fw fa-threads"
      url: "https://www.threads.net/@cathphanvan"
    - label: "BlueSky"
      icon: "fas fa-fw fa-bluesky"
      url: "https://bsky.app/profile/cathphanvan.bsky.social"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://www.facebook.com/CathPhanvan"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/CathPhanvan"

# SEO
og_image: /assets/images/logo_CPV_transparent.webp
twitter:
  username: "CathPhanvan"
facebook:
  app_id: "966242223397117"
  publisher: "105571458596033"
  username: "https://www.facebook.com/CathPhanvan"
bluesky:
  username: "cathphanvan.bsky.social"
social:
  type: Person
  name: Catherine Phan van
  links:
    - https://www.instagram.com/cathphanvan/
    - https://bsky.app/profile/cathphanvan.bsky.social
    - https://www.facebook.com/CathPhanvan
    - https://twitter.com/CathPhanvan

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-BE0T8E1ZDZ"
    anonymize_ip: false

# Search engine
google:
  search_engine_id: 36bef7c824f1e4375

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  newsletter:
    output: true
    permalink: /:collection/:path/

# Posts
posts:
  excerpt_separator: <!--excerptEnd-->

# Comments
repository: "cphanvan/cphanvan"
comments:
  provider: "custom"
  staticcomment:
    branch: "master"
reCaptcha:
  siteKey: "6LdEVV0gAAAAANITsQkgni5NVzUT3V3rwrHvFIb6"

# Site Footer
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/cathphanvan/"
    - label: "Threads"
      icon: "fas fa-fw fa-threads"
      url: "https://www.threads.net/@cathphanvan"
    - label: "BlueSky"
      icon: "fas fa-fw fa-bluesky"
      url: "https://bsky.app/profile/cathphanvan.bsky.social"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://www.facebook.com/CathPhanvan"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/CathPhanvan"


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
